# MoveIt uses this configuration for controller management

moveit_controller_manager: moveit_simple_controller_manager/MoveItSimpleControllerManager

moveit_simple_controller_manager:
  controller_names:
    - arm_controller

  arm_controller:
    type: FollowJointTrajectory
    joints:
      - joint_1_base_rotation
      - joint_2_shoulder
      - joint_3_forearm
      - joint_4_wrist
      - joint_5_hand