# This config file is used by ros2_control
controller_manager:
  ros__parameters:
    update_rate: 100  # Hz

    arm_controller:
      type: joint_trajectory_controller/JointTrajectoryController


    joint_state_broadcaster:
      type: joint_state_broadcaster/JointStateBroadcaster

arm_controller:
  ros__parameters:
    joints:
      - joint_1_base_rotation
      - joint_2_shoulder
      - joint_3_forearm
      - joint_4_wrist
      - joint_5_hand
    command_interfaces:
      - position
    state_interfaces:
      - position
      - velocity